[server]
host = "0.0.0.0"
node_port = 9001
backend_port = 9002
debug = false

[logging]
level = "debug"
folder = "logs"
force_color = true
mongodb = true

[database]
mongodb_uri = ""
database = "honeybee"
collection = "logs"
honeypot_database = "honeybee_honeypots"
honeypot_collection = "pot_logs"

[proxy]
enabled = true
host = "0.0.0.0"
port = 9003